### PR TITLE
CAN-7714 Add top margin in linechart

### PR DESCRIPTION
**Pull request by areksvk**
pridal som vlastnost MARGIN_TOP, ale bola tam uz vlastnost s nazvom MARGIN, ktora predstavuje ten spodny margin, ak tomu spravne rozumiem, preto som ju premenoval na MARGIN_BOTTOM.

### CODE REVIEW

**Comment by mattesCZ** [comment]
It looks good to me. Is it possible to set top margin somehow with `options` object?

**Comment by ondrejvelisek** [comment]
> Is it possible to set top margin somehow with `options` object?
I do not think so. 
Anyway code looks good. Just thinking where did we get the value 13?

**Comment by mattesCZ** [comment]
I think it's just updated design - 28 was too much on top, 13 is enough. I'll merge it.

**Comment by areksvk** [comment]
> I think it's just updated design - 28 was too much on top, 13 is enough. I'll merge it.

it was 50 on top actually. 28 is bottom margin.

**Pull request merged**
